### ISSUE TITLE
Uploadz challange 

### ISSUE THREAD

**Issue by matrixbot123** [ixSly/CTFs#1]
can you please elaborate how did you find the race condition? . More details on exploiting it.

**Comment by ixSly** [comment]
Hi, 

Two things:
1- You need to think about this as a basic file upload vulnerability, the code below uploads the file into the temp dir as is (without changing the name nor the extension)
```php
function create_temp_file($temp,$name){
    $file_temp = "storage/app/temp/".$name;
    copy($temp,$file_temp);
    
    return $file_temp;
  }
```
2- The goal is the achieve an RCE, so you need to upload a file that you know will be executed from the server side, in this case a PHP file, the issue was whenever you're uploading a PHP file, it is not executable due to the available .htaccess file on the server. To solve this you need to upload an .htaccess file from that executes images as PHP
`AddType application/x-httpd-php .jpg`, once that is done you can upload your shell with .jpg extension. 

Then, the server sleeps for for one second, which gives us room for a race condition, it deletes the the source file from the temp directory afterwards, hence we need to be quick, which is why I am using threading in my PoC.

```php
sleep(1);// for loadblance and anti brute
unlink($source);
```
